case erlang:function_exported(rebar3, main, 1) of
    true -> % rebar3
        CONFIG;
    false -> % rebar 2.x or older
        %% Rebuild deps, possibly including those that have been moved to
        %% profiles
        [{deps, [
            {bear, ".*", {git, "https://github.com/folsom-project/bear.git", {tag, "0.8.3"}}},
            {meck, ".*", {git, "https://github.com/eproxus/meck", {tag, "0.8.4"}}}
        ]} | lists:keydelete(deps, 1, CONFIG)]
end.

